# Generated by Django 5.2.9 on 2025-12-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
