# Generated by Django 5.2.9 on 2025-12-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auditlog_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
