# Generated by Django 5.2.9 on 2025-12-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auditlog_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
